name: Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Unit Test
        run: mvn test --batch-mode --fail-at-end

      - name: Surefire Report
        uses: ScaCap/action-surefire-report@v1.3.1

      - name: Build & push the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.docker_repository}}:${GITHUB_RUN_NUMBER}
          echo ${{ secrets.docker_secret }} | docker login --username ${{ secrets.docker_username }} --password-stdin
          docker push ${{ secrets.docker_repository}}:${GITHUB_RUN_NUMBER}